import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative ${poppins.className}`}>
        <div className="flex flex-col max-w-xl min-h-screen py-4 mx-auto">
          <Header />
          <main className=" my-4 flex-1">{children}</main>
          <Footer />
        </div>
        <div className="fixed inset-0 z-[-1] bg-gradient-to-t from-primary to-base-300" />
      </body>
    </html>
  );
}
